[workspace]
members = ["bevy_spacetimedb", "macros", "example_app"]

[workspace.dependencies]
bevy = { version = "0.17", default-features = false, features = [
    "std",
    "bevy_log",
] }
spacetimedb-sdk = { version = "1.5.0" }
